---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "airflow.fullname" . }}-configmap
data:
  airflow.cfg: |
    [core]
    airflow_home = /root/airflow
    dags_folder = /root/airflow/dags
    base_log_folder = /root/airflow/logs
    logging_level = INFO
    executor = KubernetesExecutor
    parallelism = 32
    plugins_folder = /root/airflow/plugins
    sql_alchemy_conn = $SQL_ALCHEMY_CONN

    [scheduler]
    dag_dir_list_interval = 60
    child_process_log_directory = /root/airflow/logs/scheduler

    [kubernetes]
    airflow_configmap = airflow-configmap
    worker_container_repository = {{ .Values.image.repository }}
    worker_container_tag = {{ .Values.image.tag }}
    delete_worker_pods = True
    git_repo = {{ .Values.git.repo }}
    git_branch = {{ .Values.git.branch }}
    git_subpath = {{ .Values.git.subpath }}
    git_user = {{ .Values.git.user }}
    git_password = {{ .Values.git.password }}
    dags_volume_claim = {{ template "airflow.fullname" . }}-dags

    [kubernetes_secrets]
    SQL_ALCHEMY_CONN = airflow-secrets=sql_alchemy_conn
